DROP TABLE meals;
DROP TABLE meal_entries;
DROP TABLE exercise_entries;
DROP TABLE sleep_entries;
DROP TABLE meal_types;
DROP TABLE foods;
DROP TABLE exercise_types;
DROP TABLE entries;
DROP TABLE users;
