[package]
name = "fodmap"
version = "0.1.0"
authors = ["Hayden Hughes <hayden@vulpes.chickenkiller.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.2"
rocket_contrib = { version = "0.4.2", features = ["tera_templates", "diesel_postgres_pool"] }
diesel = { version = "1.4.3", features = ["postgres"] }
bcrypt = "0.6.1"
clap = "2.33.0"
